---
name: "Reports"
guid: "d4312cd9-5c90-4f38-82e8-51da566790e8"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-reports.png"
version: 17
targetAbi: "10.9.0.0"
framework: "net8.0"
owner: "jellyfin"
overview: "Generate reports of your media library"
description: "Generate reports of your media library"
category: "General"
artifacts:
  - "Jellyfin.Plugin.Reports.dll"
  - "ClosedXML.dll"
  - "DocumentFormat.OpenXml.dll"
  - "ExcelNumberFormat.dll"
  - "System.IO.Packaging.dll"
  - "SixLabors.Fonts.dll"
changelog: |-
  - put that thing in the correct place (#85) @crobibero

  ### Bug Fixes ###
  - add reference to SixLabors.Fonts.dll (#84) @crobibero
