---
name: "Reports"
guid: "d4312cd9-5c90-4f38-82e8-51da566790e8"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-reports.png"
version: 18
targetAbi: "10.11.0.0"
framework: "net9.0"
owner: "jellyfin"
overview: "Generate reports of your media library"
description: "Generate reports of your media library"
category: "Administration"
artifacts:
  - "Jellyfin.Plugin.Reports.dll"
  - "ClosedXML.dll"
  - "ClosedXML.Parser.dll"
  - "DocumentFormat.OpenXml.dll"
  - "DocumentFormat.OpenXml.Framework.dll"
  - "ExcelNumberFormat.dll"
  - "System.IO.Packaging.dll"
  - "SixLabors.Fonts.dll"
  - "RBush.dll"
changelog: |-
  - Jellyfin 10.11 support (#98) @crobibero
  - fix: require admin privileges to access reports API (#95) @Theta-Dev

  ### Code or Repo Maintenance ###
  - Fix Overlay Button Accessibility  (#91) @a-mnich
